apiVersion: v1
kind: Service
metadata:
  name: guestbook-app-service
  labels:
    name: guestbook-app-service
    app: guestbook-app
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 3000
  selector:
    name: guestbook-app-deployment
    app: guestbook-app
