apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: guestbook-app-deployment
  labels:
    app: guestbook-app
    type: front-end
spec:
  template:
    metadata:
      name: guestbook-app-pod
      labels:
        name: guestbook-app-deployment
        app: guestbook-app
        type: front-end
    spec:
      containers:
        - name: guestbook-app-container
          image: kubernetes/guestbook:v2
          ports:
            - containerPort: 3000
  replicas: 3
  selector:
    matchLabels:
      app: guestbook-app
