apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: redis-deployment
  labels:
    name: redis-deployment
    app: guestbook-app
    type: back-end
spec:
  template:
    metadata:
      name: redis-pod
      labels:
        app: guestbook-app
        type: back-end
    spec:
      containers:
      - name: redis
        image: redis
        ports:
        - containerPort: 6379
  selector:
    matchLabels:
      app: guestbook-app
